name: advent2024
version: 0.1.0.0
github: "cdparks/advent2024"
license: BSD-3-Clause
author: "Christopher D. Parks"
maintainer: "christopher.daniel.parks@gmail.com"
copyright: "2024 Christopher D. Parks"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/githubuser/advent2024#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- BangPatterns
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- DisambiguateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoFieldSelectors
- NoImplicitPrelude
- NoStarIsType
- OverloadedStrings
- OverloadedRecordDot
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - containers
  - extra
  - filepath
  - hashable
  - hspec
  - hspec-api
  - microlens
  - microlens-mtl
  - monoidal-containers
  - mtl
  - parallel
  - safe
  - text
  - time
  - unliftio
  - unliftio-core
  - unordered-containers
  - vector

executables:
  advent2024:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2024
